[toolchain]
anchor_version = "0.32.1"

[toolbox]
network = "devnet"
wallet = "/home/dane/solana-wallet.json"

[provider]
cluster = "devnet"
wallet = "/home/dane/solana-wallet.json"

[programs.localnet]
x402_fun = "63NAXuGHqn4nYu9kHiucsEdkgVobZ3dhtGHpaVDE7XJF"

[programs.devnet]
x402_fun = "63NAXuGHqn4nYu9kHiucsEdkgVobZ3dhtGHpaVDE7XJF"

[registry]
url = "https://api.apr.dev"

[plugin.extras]
git_hash = ""
